apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: back
  name: back
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      io.kompose.service: back
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: back
    spec:
      containers:
      - image: bondarieva/quotes-back:v1.2
        name: api
        env:
        - name: SQLALCHEMY_DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: back-secret
              key: dburl
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
