apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.7.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: front
  name: front
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      io.kompose.service: front
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: front
    spec:
      containers:
      - image: bondarieva/quotes-front:v1
        name: front
        ports:
        - containerPort: 3001
        resources: {}
      restartPolicy: Always
status: {}
